# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "My Corne Config"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      # shield: '["xiao_corne_v2_left","xiao_corne_v2_right"]'
      shield: '["absolem_left","absolem_right"]'
      # kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
